[project]
name = "clip-sanw"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "torch>=2.2.0",
  "torchvision>=0.17.0",
  "open_clip_torch>=2.26.2",
  "tqdm>=4.66.0",
  "numpy>=1.24.0",
  "pandas>=2.1.0",
  "pyyaml>=6.0.1",
  "scikit-learn>=1.3.0",
]
