# Cluster-specific SANW-Bandpass configuration
seed: 13
model_dir: openai/clip-vit-base-patch32
batch_size: 128
num_workers: 0  # Set to 0 for cluster compatibility
epochs: 20
lr: 5.0e-4
wd: 0.2
amp: true
log_every: 20
experiment_name: "bandpass"

loss:
  name: sanw_bandpass
  alpha: 0.5
  m1: 0.3
  m2: 0.8
  gamma: 0.05

dataset:
  name: flickr8k
  root: /nfs_home/users/poonam/clipse/data/flickr8k
  topical:
    enabled: true
    k: 80
