exp_name: flickr8k_vitb32_debias
seed: 42
device: cuda
output_dir: runs/flickr8k_vitb32_debias
model: { name: ViT-B-32, pretrained: openai }
data:
  flickr8k: { root: data/flickr8k, tsv: captions.tsv }
  batch_size: 64
  num_workers: 4
  topical_batches: true
  topical_key: noun
optim: { lr: 5.0e-5, weight_decay: 0.2, epochs: 8, grad_clip: 1.0 }
loss:
  name: sanw
  mode: debias
  alpha: 0.5
  delta: 0.6
  lam: 4.0
  temperature_learnable: true
eval: { retrieval_every_epochs: 1, zs_cifar10: true, val_subset: 1000 }
log: { interval: 50 }
