exp_name: flickr8k_sanw_debias
seed: 13
device: cuda
output_dir: runs/flickr8k_sanw_debias
epochs: 20
model:
  name: ViT-B-32
  pretrained: openai
data:
  flickr8k:
    root: data/flickr8k
    tsv: captions.tsv
  batch_size: 128
  num_workers: 4
  topical_batching:
    enabled: true
    p_topical: 0.6
    k_clusters: 80
    refresh_every_epochs: 20
    sampler_temperature: 0.7
optim:
  name: adamw
  lr: 0.0005
  betas: [0.9, 0.98]
  eps: 0.000001
  weight_decay: 0.2
  grad_clip: 1.0
scheduler:
  name: cosine
  warmup_epochs: 1
loss:
  name: sanw_debias
  alpha: 0.5
  delta: 0.6
  lambda: 4.0
  stopgrad_weights: true
  geometry_align:
    enabled: false
logit_scale:
  init: 2.659
  clamp_max: 4.605170
precision: amp
curriculum:
  enabled: true
  switch_epoch: 12
eval:
  metrics: [R@1, R@5, R@10]
  directions: [i2t, t2i]
  every_epochs: 1
save:
  metric: mean_R1
log:
  interval: 50
