#!/bin/bash
# Manual setup instructions for remote GPU server

echo "🚀 Manual Setup Instructions for Remote GPU Server"
echo "=================================================="
echo ""
echo "1. First, connect to the remote server:"
echo "   ssh priyank@172.24.16.130"
echo "   (Password: priyank@123#)"
echo ""
echo "2. Once connected, create the project directory:"
echo "   mkdir -p ~/clipse"
echo "   cd ~/clipse"
echo ""
echo "3. Install Python dependencies:"
echo "   pip install torch torchvision open-clip-torch timm numpy pandas scikit-learn Pillow tqdm PyYAML matplotlib seaborn"
echo ""
echo "4. Check CUDA availability:"
echo "   python -c \"import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA devices: {torch.cuda.device_count()}')\""
echo ""
echo "5. Transfer the code from your local machine:"
echo "   (From your local terminal, run the following commands:)"
echo ""
echo "   # Create a tar archive of the code"
echo "   cd /Users/priyankjairaj/Downloads/clipse"
echo "   tar -czf clipse_code.tar.gz --exclude='runs' --exclude='data/cifar10' --exclude='__pycache__' --exclude='*.pyc' ."
echo ""
echo "   # Transfer to remote server"
echo "   scp clipse_code.tar.gz priyank@172.24.16.130:~/clipse/"
echo ""
echo "6. On the remote server, extract the code:"
echo "   cd ~/clipse"
echo "   tar -xzf clipse_code.tar.gz"
echo "   rm clipse_code.tar.gz"
echo ""
echo "7. Run the experiments:"
echo "   python run_all_experiments.py"
echo ""
echo "8. After experiments complete, analyze results:"
echo "   python analyze_results.py"
echo ""
echo "9. To transfer results back to local machine:"
echo "   scp -r priyank@172.24.16.130:~/clipse/runs/ /Users/priyankjairaj/Downloads/clipse/"
echo "   scp priyank@172.24.16.130:~/clipse/results_*.txt /Users/priyankjairaj/Downloads/clipse/"
echo "   scp priyank@172.24.16.130:~/clipse/results_*.tex /Users/priyankjairaj/Downloads/clipse/"
echo ""
echo "✅ Setup complete!"
