# SANW-Bandpass CLIP training configuration
seed: 13
model_dir: ${MODEL_DIR}
batch_size: 256
num_workers: 4
epochs: 20
lr: 5.0e-4
wd: 0.2
amp: true
log_every: 20
experiment_name: "bandpass"

loss:
  name: sanw_bandpass
  alpha: 0.5
  m1: 0.3
  m2: 0.8
  gamma: 0.05

dataset:
  name: flickr8k
  root: ${DATASET_ROOT}
  topical:
    enabled: true
    k: 80
