name: Test Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test imports
      run: |
        python -c "import src.train; import src.losses; import src.datasets; import src.eval_utils; print('All imports successful')"
    
    - name: Test config loading
      run: |
        python -c "
        import yaml
        configs = ['configs/flickr8k_vitb32_baseline.yaml', 'configs/flickr8k_vitb32_debias.yaml', 'configs/flickr8k_vitb32_bandpass.yaml']
        for cfg in configs:
            with open(cfg, 'r') as f:
                yaml.safe_load(f)
            print(f'✓ {cfg} loads successfully')
        print('All configs valid')
        "
